/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "rcc_int.h"
#include "Systick_config.h"
#include "DIO_interface.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#define FCPU 8000000
void App(void);
int main(void)
{
	MRCC_voidInit();
	MRCC_enumSetPeripheralClock(APB2 , IOPBEN_ID, RCC_ENABLE );
	GPIO_voidSetPortnDirection(PORTB, GPIO_OUTPUT_2MHZ_PP);
	SYSTICK_SetCallback(App);
	SYSTICK_Init();
//	SYSTICK_SetTime_ms(1000,8000000);
	SYSTICK_SetTime(5000,8000000);
	SYSTICK_Start();
//	GPIO_voidSetPinValue(PORTB,5,LOGIC_HIGH);
//	SYSTICK_SetTime_ms(1000.0,1000000.0);
    /* Loop forever */
	for(;;)
	{
	//	GPIO_voidSetPinValue(PORTB,5,LOGIC_HIGH);
//		GPIO_voidTogglePin(PORTB,5);

//		GPIO_voidTogglePin(PORTB,0);
//		SYSTICK_SetTime_ms(1000,1000000);
	}
	return 0;
}

void App(void)
{
	GPIO_voidTogglePin(PORTB,2);
//	GPIO_voidSetPinValue(PORTB,5,LOGIC_LOW);
}





