/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>
#include "rcc_int.h"
#include "NVIC.h"
#include "DIO_interface.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void ADC1_2_IRQHandler(void) __attribute__((interrupt));
void USART1_IRQHandler(void) __attribute__((interrupt));
void WWDG_IRQHandler(void) __attribute__((interrupt));
int main(void)
{
	MRCC_voidInit();
	MRCC_enumSetPeripheralClock(APB2 , IOPBEN_ID, RCC_ENABLE );
	GPIO_voidSetPortnDirection(PORTB, GPIO_OUTPUT_2MHZ_PP);
	DNVIC_EnableIRQ(ADC1_2);
	DNVIC_EnableIRQ(USART1);
	DNVIC_EnableIRQ(WWDG);
	DNVIC_SetPriorityGrouping(TWO_PREEMPTION_TWO_SUBGROUP);
	DNVIC_SetPriority(ADC1_2, 0x00, 0x00);
	DNVIC_SetPriority(USART1, 0x02, 0x03);
	DNVIC_SetPriority(WWDG, 0x01, 0x02);

	uint8 i = 0;
    /* Loop forever */
	for(;;)
	{
		GPIO_voidTogglePin(PORTB,5);
		while(i >=1000000)
		{
			i++;
		}
		i=0;
		//delay HAL_Delay(1000);
		DNVIC_SetPendingIRQ(ADC1_2);
		//delay
//		GPIO_voidTogglePin(PORTB,5);
		//delay
		DNVIC_SetPendingIRQ(USART1);
		//delay
//		GPIO_voidTogglePin(PORTB,5);
		//delay
		DNVIC_SetPendingIRQ(WWDG);
		//delay

	}
}

void  ADC1_2_IRQHandler(void)
{
	DNVIC_ClearPendingIRQ(ADC1_2);
	uint8 i = 0;
	GPIO_voidTogglePin(PORTB, 0);
	while(i >=1000000)
	{
		i++;
	}
	i=0;
}
void USART1_IRQHandler(void)
{
	DNVIC_ClearPendingIRQ(USART1);
	uint8 i = 0;
	GPIO_voidTogglePin(PORTB, 1);
	while(i >=1000000)
	{
		i++;
	}
	i=0;
}
void WWDG_IRQHandler(void)
{
	DNVIC_ClearPendingIRQ(WWDG);
	uint8 i = 0;
	GPIO_voidTogglePin(PORTB, 2);
	while(i >=1000000)
	{
		i++;
	}
	i=0;
}
